---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svcb-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svcb
        version: v2
    spec:
      containers:
      - name: svcb
        command: ["/root/svcb/svcb", "-msgsvc", "192.168.137.102:9997"]
        image: bigwhite/istio-demo-svcb:v0.2
        imagePullPolicy: Never


