apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svcb-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svcb
        version: v1
    spec:
      containers:
      - name: svcb
        command: ["/root/svcb/svcb", "-msgsvc", "192.168.137.102:9997"]
        image: bigwhite/istio-demo-svcb:v0.1
        imagePullPolicy: Never
        

---
apiVersion: v1
kind: Service
metadata:
  name: svcb
  labels:
    app: svcb
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: svcb
